### ISSUE TITLE
Package.xml is not capturing when we change <enableFeeds> value in objects

### ISSUE THREAD

**Issue by nithyusha23** [amtrack/force-dev-tool#112] opened 2018-01-22 08:17 UTC
We have changed <enableFeeds>true</enableFeeds> value to <enableFeeds>false </enableFeeds> in objects and when executed package.xml, it did not identify the above change and created an empty xml file.

`<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>38.0</version>
</Package>
`

**Comment by nithyusha23** [comment] 2018-01-23 15:39
Anybody has seen this issue already. If yes, please let me know if you found any solution for this issue.

**Comment by amtrack** [comment] 2018-01-28 16:05
Hi @nithyusha23 ,

yes i'm aware of this.

Related issues: #90, #13

**Comment by nithyusha23** [comment] 2018-01-29 09:24
Could you please let us know if there are any other issues as such , so that we do not face any sudden surprises.

**Comment by amtrack** [comment] 2019-04-04 08:53
duplicate of #90, #13

**Closed by amtrack** 2019-04-04 08:53 UTC
