### ISSUE TITLE
Package.xml is not capturing changes of customSettingAccesses and customMetadataTypeAccesses in Profiles

### ISSUE THREAD

**Issue by joshnarani** [amtrack/force-dev-tool#224] opened 2020-02-24 16:51 UTC
Salesforce sent an update to add customSettingAccesses and customMetadataTypeAccesses in Profiles, when trying to deploy the package is not getting created for these changes, its creating blank package.

**Comment by amtrack** [comment] 2020-02-27 10:02
duplicate of #218

**Closed** 2020-02-27 10:02 UTC
