### ISSUE TITLE
diff resulting to high number of files takes a long time

### ISSUE THREAD

**Issue by okram999** [amtrack/force-dev-tool#93] opened 2017-07-18 16:16 UTC
hi @amtrack my git diff returns like 565 files, and the generating the package.xml like `force-dev-tool changeset create devDeploy`  takes forever, it is still running.. is there a way how i can make this faster. May be feed in more memory to the node??  

 force-dev-tool@0.13.1

**Comment by okram999** [comment] 2017-07-18 21:29
still running after 4hrs :(

**Comment by amtrack** [comment] 2017-07-18 21:32
Sounds wrong to me. Did you really pipe in the git diff?

**Comment by okram999** [comment] 2017-07-19 04:19
@amtrack , i wish i am wrong. As i find your tool so cool and really want to give it a try. Here is what i have as a part of the shell script

`node --version
npm install --global force-dev-tool
force-dev-tool --help
git fetch --all
git branch -a
git checkout master
git checkout config2
git diff master config2 | force-dev-tool changeset create devDeploy`

**Comment by okram999** [comment] 2017-07-19 04:37
So, i just removed the force-dev-tool 's changeset create section from the pipe, and ran just the diff, the diff is okay. 

node --version
npm install --global force-dev-tool
git fetch --all
git branch -a
git checkout master
git checkout config2
git diff master config2 #| force-dev-tool changeset create devDeploy

I am going to save the diff into a file and pipe it in the force-dev-tool, and see what happens?

**Comment by okram999** [comment] 2017-07-19 04:45
The output file from the git diff is 108MB and there are 3005097 lines.. is this the reason? Won't it better if, you pipe in the `git diff --name-only` ?

**Comment by okram999** [comment] 2017-07-19 19:17
We removed a component from vesioning. It was contributing to around 359 files in the git diff. Now force-dev-tool is generating the package.xml

**Comment by amtrack** [comment] 2017-07-25 15:15
OK, so i didn't run any performance tests but as far as i can tell parsing the diff shouldn't be the bottleneck. However I can confirm that parsing and preparing the files seems to be not so performant at the moment.
Do you want to contribute on this issue by creating a test repo or improving the code itself?

**Comment by okram999** [comment] 2017-07-25 15:22
yes, i will have to see how i can get a similarly sized repo, where i am having the issue by scrapping any confidential info

**Comment by amtrack** [comment] 2017-07-25 15:39
Sounds good! Let me know if I can help.
I would be happy to talk to you about your use cases btw to see what else can be improved :-)

**Comment by okram999** [comment] 2017-08-01 20:31
anything in the v1.0, which you think have improved the "parsing and preparing the files "

**Comment by okram999** [comment] 2017-08-02 16:02
i am not there yet, but i am kind of thinking this might be due to the objectTranslation 's content and the regex that you defined to build the package.xml ... will update more

**Comment by amtrack** [comment] 2018-01-07 13:34
Closed by #99 .

**Closed by amtrack** 2018-01-07 13:34 UTC

**Comment by Nazareena** [comment] 2018-05-02 06:44
When trying force-dev-tool changeset with cli arguments having custom field metadata the package build the complete Account object rather than having only the field, do we have any fix for this example command is as below 
force-dev-tool changeset create vat src/pages/AccountExtensionVAT.page CustomField/Account.VAT__c
